import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import downloadImage from "../assets/images/shiva.jpg";
import Image from "next/image";
import Rating from "@/component/Rating";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <script
          src="https://kit.fontawesome.com/a076d05399.js"
          crossorigin="anonymous"
        ></script>
      </Head>
      <div className={styles.portfolio_page}>
        <div className={styles.main_page}>
          <div className={styles.left_side_bio}>
            <div className={styles.profile_image}>
              <Image
                src={downloadImage}
                alt="Download"
                width={300}
                height={200}
              />
              <p className={styles.profile_title}>React Developer</p>
              <div className={styles.education_details}>
                <h5 className={styles.heading_5}>Education</h5>
                <div className="education_first">
                  <h6 className={styles.heading_6}>
                    M.C.A (Master Of Computer Application)
                  </h6>
                  <p>Govt. Jabalpur Engneering Collage jabalpur 2014-2016</p>
                </div>
                <div className="education_second">
                  <h6 className={styles.heading_6}>
                    B.C.A (Bachlor Of Computer Application)
                  </h6>
                  <p>Awadesh Pratap Singh University Rewa 2011-2014</p>
                </div>
              </div>
            </div>
            <div className={styles.left_side_btm}>
              <div className={styles.expertise}>
                <h5 className={styles.heading_5}>Expertise</h5>
                <div className={styles.ext_row}>
                  <span>Reactjs</span>
                  <span className={styles.rating}>
                    <Rating />
                  </span>
                </div>
                <div className={styles.ext_row}>
                  <span>Angular 4+</span>
                  <span className={styles.rating}>
                    <Rating />
                  </span>
                </div>
                <div className={styles.ext_row}>
                  <span>html/html5</span>
                  <span className={styles.rating}>
                    <Rating />
                  </span>
                </div>
                <div className={styles.ext_row}>
                  <span>Css/Css3</span>
                  <span className={styles.rating}>
                    <Rating />
                  </span>
                </div>
                <div className={styles.ext_row}>
                  <span>javascript</span>
                  <span className={styles.rating}>
                    <Rating />
                  </span>
                </div>
                <div className={styles.ext_row}>
                  <span>Nextjs</span>
                  <span className={styles.rating}>
                    <Rating />
                  </span>
                </div>
                <div className={styles.ext_row}>
                  <span>Redux</span>
                  <span className={styles.rating}>
                    <Rating />
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.right_side_info}>
            <div className={styles.pt_header}>
              <h1>
                Shivakant <span>Tiwari</span>
              </h1>
              <p className={styles.job_title}>React Developer</p>
              <h5 className={styles.heading_5}>profile</h5>
              <p>
                A highly qualified software engineer with a passion for
                problem-solving and a commitment to providing quality software
                solutions. Seeking to join ABC Company and use my knowledge and
                experience to create innovative solutions.
              </p>
            </div>
            <div className={styles.work_exp}>
              <h5 className={styles.heading_5}>Work Experience</h5>
              <div className={styles.experiance}>
                <h6 className={styles.heading_6}>
                  Working as Reactjs & Nextjs Developer
                </h6>
                <div className={styles.company_info}>
                  <span className={styles.yell_box}>Present - 2021</span>
                  <span>Yuvasoft Solution Pvt. Ltd. Navlakha(indore)</span>
                </div>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever
                </p>
              </div>
              <div className={styles.experiance}>
                <h6 className={styles.heading_6}>
                  PHP Developer / Wordpress Developer
                </h6>
                <div className={styles.company_info}>
                  <span className={styles.yell_box}>2019-2021</span>
                  <span>
                    Conative It Solution Pvt. Ltd. Industry House(indore)
                  </span>
                </div>
                <p>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever
                </p>
              </div>
            </div>
            <div className={styles.interest}>
              <h5 className={styles.heading_5}>interest</h5>
              <div className={styles.interest_list}>
                <div className={styles.common_st}>
                  <span>
                    <i class="fa fa-globe"></i>
                  </span>
                  <span>Travel</span>
                </div>
                <div className={styles.common_st}>
                  <span>
                    <i class="fa fa-music"></i>
                  </span>
                  <span>Music</span>
                </div>
                <div className={styles.common_st}>
                  <span>
                    <i class="fa fa-file"></i>
                  </span>
                  <span>Writing</span>
                </div>
                <div className={styles.common_st}>
                  <span>
                    <i class="fa fa-cubes"></i>
                  </span>
                  <span>Sports</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
