import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import downloadImage from "../assets/images/shiva.jpeg";
import Image from "next/image";
import Rating from "@/component/Rating";
import {
  EducationArray,
  Experience,
  TechnologyArray,
  intrestArray,
} from "@/constant/allData";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <script
          src="https://kit.fontawesome.com/a076d05399.js"
          crossorigin="anonymous"
        ></script>
      </Head>
      <div className={styles.portfolio_page}>
        <div className={styles.main_page}>
          <div className={styles.left_side_bio}>
            <div className={styles.profile_image}>
              <Image
                src={downloadImage}
                alt="Download"
                width={300}
                height={200}
              />
              <p className={styles.profile_title}>React Developer</p>
              <div className={styles.education_details}>
                <h5 className={styles.heading_5}>Education</h5>
                {EducationArray?.map((element, index) => {
                  return (
                    <div className="education" key={index}>
                      <h6 className={styles.heading_6}>{element.courseName}</h6>
                      <p>{element.collageName}</p>
                    </div>
                  );
                })}
              </div>
            </div>
            <div className={styles.left_side_btm}>
              <div className={styles.expertise}>
                <h5 className={styles.heading_5}>Expertise</h5>
                {TechnologyArray.map((item, index) => {
                  return (
                    <div key={index} className={styles.ext_row}>
                      <span>{item.techName}</span>
                      <span className={styles.rating}>
                        <Rating />
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
          <div className={styles.right_side_info}>
            <div className={styles.pt_header}>
              <h1>
                Shivakant <span>Tiwari</span>
              </h1>
              <p className={styles.job_title}>React Developer</p>
              <h5 className={styles.heading_5}>profile</h5>
              <p>
                A highly qualified software engineer with a passion for
                problem-solving and a commitment to providing quality software
                solutions. Seeking to join ABC Company and use my knowledge and
                experience to create innovative solutions.
              </p>
            </div>
            <div className={styles.work_exp}>
              <h5 className={styles.heading_5}>Work Experience</h5>
              {Experience?.map((element, index) => {
                return (
                  <div className={styles.experiance} key={index}>
                    <h6 className={styles.heading_6}>{element.jobTitle}</h6>
                    <div className={styles.company_info}>
                      <span className={styles.yell_box}>{element.session}</span>
                      <span>{element.companyName}</span>
                    </div>
                    <p>{element.aboutExperince}</p>
                  </div>
                );
              })}
            </div>
            <div className={styles.interest}>
              <h5 className={styles.heading_5}>interest</h5>
              <div className={styles.interest_list}>
                {intrestArray?.map((ele, index) => {
                  return (
                    <div className={styles.common_st}>
                      <span>{ele.icon}</span>
                      <span>{ele.int_name}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
